name: Build & Test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    uses: TheKingOfLettuce/LettuceGithubWorkflows/.github/workflows/Build-dotnet.yml@main
    with:
      dotnet-version: 10.0.x
      configuration: Release
      project-path: Lettuce.Log.File/Lettuce.Log.File.csproj
  test:
    needs: build

    uses: TheKingOfLettuce/LettuceGithubWorkflows/.github/workflows/Test-dotnet.yml@main
    with:
      dotnet-version: 10.0.x
      configuration: Release
      project-path: Lettuce.Log.File.Tests/Lettuce.Log.File.Tests.csproj